- .github/dependabot.yml
- src/app.postcss
- src/lib/components/Navigation.svelte
- src/lib/components/explorer/Checkbox.svelte
- src/routes/admin/+page.svelte
- src/routes/admin/authentication/+page.svelte
- src/routes/admin/authorization/+page.svelte
- tests/lib/component/navigation/test.ts
- Change keyboard navigation to standard menu bar instead of application bar.
> [ALS-6146] Add menu dropdowns

- src/lib/components/admin/authorization/PrivilegeForm.svelte
- src/lib/components/admin/authorization/RoleForm.svelte
- src/lib/components/admin/authorization/cell/Application.svelte
- src/lib/components/admin/authorization/cell/PrivilegeActions.svelte
- src/lib/components/admin/authorization/cell/RoleActions.svelte
- src/lib/models/Applications.ts
- src/lib/models/Privileges.ts
- src/lib/models/User.ts
- src/lib/stores/Application.ts
- src/lib/stores/Privileges.ts
- src/lib/stores/Roles.ts
- src/lib/stores/Users.ts
- src/lib/stores/mock/data.ts
- src/routes/admin/authorization/+page.svelte
- src/routes/admin/authorization/privilege/[uuid]/+page.svelte
- src/routes/admin/authorization/privilege/[uuid]/edit/+page.svelte
- src/routes/admin/authorization/privilege/new/+page.svelte
- src/routes/admin/authorization/role/[uuid]/+page.svelte
- src/routes/admin/authorization/role/[uuid]/edit/+page.svelte
- src/routes/admin/authorization/role/new/+page.svelte
- tests/mock-data.ts
- tests/routes/admin/authorization/test.ts
- tests/routes/user/test.ts
*Note:* Check that branch PR pointing to dev after merging PR for feature/menu-dropdown.
> [ALS-6146] Add authorization page and subpages

- .github/workflows/tests.yml
- src/lib/components/explorer/dataExport/ExportStepper.svelte
- src/lib/models/query/Query.ts
> Add Lint tests for PRs

- package-lock.json
- package.json
- src/app.postcss
- src/lib/components/QuerySummary.svelte
- src/lib/components/VerticalStepper.svelte
- src/lib/components/request/Grid.svelte
- src/lib/components/request/GridCell.svelte
- src/lib/components/request/modals/DataLocModal.svelte
- src/lib/components/request/modals/DataSummary.svelte
- src/lib/components/request/modals/DataTypeModal.svelte
- src/lib/components/request/modals/SendDataModal.svelte
- src/lib/configuration.ts
- src/lib/models/DataRequest.ts
- src/lib/models/Privilege.ts
- src/lib/stores/DataRequest.ts
- src/lib/stores/Search.ts
- src/lib/utilities/Validation.ts
- src/routes/(picsure)/(authorized)/(admin)/admin/requests/+page.svelte
- src/routes/(picsure)/(authorized)/dataset/[uuid]/+page.svelte
- tests/mock-data.ts
- tests/routes/admin/requests/test.ts
- tests/routes/admin/users/test.ts
- Move data summary code into shared component for Dataset and Data Requests page.
- Move user test files into tests/admin folder.
> [ALS-6347] Add Data request page, models and stores

- src/lib/components/Content.svelte
- src/lib/components/admin/authorization/cell/PrivilegeActions.svelte
- src/lib/components/admin/authorization/cell/RoleActions.svelte
- src/lib/components/admin/user/cell/Actions.svelte
- src/lib/components/buttons/AngleButton.svelte
- src/lib/components/buttons/CopyButton.svelte
- src/lib/components/dataset/cell/Actions.svelte
- src/lib/components/datatable/Row.svelte
- src/lib/components/datatable/Table.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/authorization/+page.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/authorization/privilege/[uuid]/+page.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/authorization/privilege/[uuid]/edit/+page.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/authorization/privilege/new/+page.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/authorization/role/[uuid]/+page.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/authorization/role/[uuid]/edit/+page.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/authorization/role/new/+page.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/users/+page.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/users/[uuid]/+page.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/users/[uuid]/edit/+page.svelte
- src/routes/(picsure)/(authorized)/(admin)/admin/users/new/+page.svelte
- src/routes/(picsure)/(authorized)/dataset/+page.svelte
- src/routes/(picsure)/(authorized)/dataset/[uuid]/+page.svelte
- src/routes/(picsure)/(public)/explorer/genome-filter/+page.svelte
- tests/routes/admin/authorization/test.ts
- tests/routes/admin/users/test.ts
- tests/routes/dataset/test.ts
- Add back buttons on view/edit/new pages. 
- Add row click handlers to tables.
- Use buttons with click handlers instead of links to fix some weird bug where svelte store sessions get dumped while navigating.
- Force `(s)` to remain lowercase on row header `Role(s)`.
> [ALS-6146] [ALS-6325] Authorization and User management page updates.

- src/app.postcss
- src/lib/components/Navigation.svelte
- src/routes/(authentication)/login/+layout.svelte
Computed header height now ~58.8px. Deployed to GIC staging.
> [ALS-6270] Shrink header navigation and links

- src/app.postcss
- src/lib/components/explorer/results/ExportedVariable.svelte
- src/lib/components/explorer/results/ResultsPanel.svelte
- src/lib/components/explorer/results/SidePanel.svelte
- src/lib/configuration.ts
- src/lib/stores/Export.ts
- src/routes/(picsure)/(public)/explorer/+page.svelte
- src/routes/(picsure)/+layout.svelte
- tests/routes/explorer/test.ts
- Add clear-all button.
- Update styles and copy.
> [ALS-6323] Design updates for results-panel

- .env.example
- .env.test
- src/lib/api.ts
- src/lib/components/Navigation.svelte
- src/lib/configuration.ts
- src/lib/stores/User.ts
- src/routes/(authentication)/login/+page.svelte
- src/routes/(picsure)/+layout.ts
> [ALS-6840] Add feature flag for optional login

- src/app.postcss
- src/lib/components/Footer.svelte
- src/lib/components/ModalWrapper.svelte
- src/lib/components/Stats.svelte
- src/lib/components/TermsModal.svelte
- src/lib/configuration.ts
- src/lib/models/Value.ts
- src/routes/(authentication)/login/+layout.svelte
- src/routes/(picsure)/+layout.svelte
- src/routes/+layout.svelte
- src/terms.svelte
- Also fix stats loading width bug.
> [ALS-5477] Add terms modal and default text

- src/app.postcss
- src/lib/components/Footer.svelte
- src/lib/components/admin/authorization/cell/PrivilegeActions.svelte
- src/lib/components/admin/authorization/cell/RoleActions.svelte
- src/lib/components/admin/user/cell/Actions.svelte
- src/lib/components/dataset/cell/Actions.svelte
- src/lib/components/explorer/cell/Actions.svelte
- src/lib/components/explorer/results/AddedFilter.svelte
- src/lib/components/explorer/results/ExportedVariable.svelte
Some colors looked wonky in dark mode.
> [ALS-0000] Update links and button colors for dark mode

- src/lib/assets/configuration.json
- src/lib/configuration.ts
- src/routes/(picsure)/(authorized)/analyze/+page.svelte
- src/routes/(picsure)/(authorized)/analyze/example/+page.svelte
This is just copy changes really
> ALS-7300: Prepare for Analysis Page in BDC

- src/lib/components/explorer/export/ExportStepper.svelte
This is not necessary anymore, we are not even building this tab group in other cases
> ALS-7504: Fix export tabgroup

- src/lib/components/FilterWarning.svelte
- src/lib/components/explorer/results/SidePanel.svelte
- src/lib/models/Filter.ts
- src/lib/stores/Filter.ts
- src/lib/stores/SidePanel.ts
- src/routes/(authentication)/login/loading/+page.svelte
- src/routes/(picsure)/(authorized)/+layout.ts
- src/routes/(picsure)/(public)/discover/+page.svelte
- src/routes/(picsure)/+layout.svelte
- tests/mock-data.ts
- tests/routes/explorer/genomic-filter/gene-test.ts
- tests/routes/explorer/genomic-filter/snp-test.ts
- tests/routes/explorer/variant/test.ts
> [ALS-7357] Check filters on navigation

- src/lib/assets/login/NIH_2013_logo_vertical_text_removed.svg
- src/lib/components/LoginButton.svelte
- src/lib/models/AuthProvider.ts
- src/routes/(authentication)/login/+page.svelte
- static/NIH_2013_logo_vertical_text_removed.svg
The style changes are temporary and will likely be reverted in the future. The ability to include images will be kept.
> Update login button appearance and add support for dynamic images

- src/lib/components/explorer/FacetSideBar.svelte
Wrapped ProgressRadial in a flex container to center it vertically and horizontally. Added a new CSS class for consistent styling and improved visual alignment. This ensures a better user experience when the facets are loading.
> [ALS-7423] Enhance ProgressRadial alignment in FacetSideBar

- src/lib/components/Searchbox.svelte
- src/lib/components/explorer/Explorer.svelte
- tests/routes/explorer/test.ts
- Allow search button on empty search.
> [ALS-7674] Remove Facet Reset

- src/lib/components/explorer/export/ExportStepper.svelte
- src/lib/components/steppers/horizontal/Stepper.svelte
- Fixes an oddity where lastStep is not correctly indexed
> [ALS-8208] Update stepper to identify correct lastStep name for api requests

- src/lib/components/explorer/results/ResultsPanel.svelte
Enhance navigation lifecycle with subscription handling
> [ALS-8694] Fix [Object Object] Bug

- src/app.html
Reference: [OWASP Clickjacking Defense Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html#best-for-now-legacy-browser-frame-breaking-script)
> [ALS-8965] Add anti Clickjacking frame-breaker

- src/lib/components/HelpInfoPopup.svelte
- src/lib/components/Popover.svelte
- src/lib/components/admin/configuration/PrivilegeForm.svelte
- src/lib/components/admin/user/UserForm.svelte
- src/lib/components/datatable/accessories/Rows.svelte
- src/lib/components/explorer/FilterWarning.svelte
- src/lib/components/explorer/genome-filter/SNP/Edit.svelte
- src/lib/components/request/StatusIndicator.svelte
- src/lib/configuration.ts
- src/routes/(authentication)/login/+page.svelte
- src/routes/(picsure)/(authorized)/dataset/request/+page.svelte
- src/styles/app.css
This PR fixes the following bugs that resulted from adding in the Federated functionality.
- [ALS-9593] Page should not remain highlighted when returning to Explore/Discover
- [ALS-9592] Search results page number overlaps with arrow
- [ALS-9594] Prepare for Analysis page "Copy" button for token should only work on click
- [ALS-9595] User cannot navigate to Manage Datasets
- [ALS-9533] Use solid for check icon
> [CHORE] Bug Fixes

- src/lib/components/explorer/Explorer.svelte
- src/lib/stores/Search.ts
This reduces the api requests on initial page load, which also removes some misc 403 errors for users who are logging in but aren't yet logged in.
> Wrap table handler subscribers in initialization method
